### ISSUE TITLE
[错误]: 开屏时点击会造成白屏（无显示内容）

### ISSUE THREAD

**Issue by ThreeManager785** [WindowsMEMZ/SwiftArchive#10]
### 问题位置

其他

### 其他问题位置

首页

### 问题描述

如题，在刚启动App时（入场动画显示前）立刻点击屏幕，可能导致iPhone显示内容全白，无响应。

### 复现步骤

如题，在入场动画显示前立刻点击屏幕。

**Comment by WindowsMEMZ** [comment]
操作10次，未成功复现

**Comment by ThreeManager785** [comment]
很好，我也复现不出来了
