### ISSUE TITLE
[错误]: 删除项目后项目列表仍显示项目

### ISSUE THREAD

**Issue by Linecom233** [WindowsMEMZ/SwiftArchive#12]
### 问题位置

Momotalk 编辑器

### 问题描述

在项目设置长按删除后，回到主页仍显示该项目，点进后崩溃

### 复现步骤

删除项目

**Comment by Linecom233** [comment]
+删除项目后刷新项目列表

**Comment by WindowsMEMZ** [comment]
Fixed at commit `b89e6ca2`
